# Generated by Django 5.1.2 on 2024-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acct_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('acct_name', models.CharField(max_length=100)),
                ('acct_resident_num', models.BigIntegerField(blank=True, null=True)),
                ('classification', models.CharField(max_length=100)),
                ('invoice_address', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_postcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('acct_num',)},
            },
        ),
    ]
