# Generated by Django 5.1.2 on 2024-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acct_name',
            field=models.CharField(max_length=100),
        ),
    ]
