# Generated by Django 5.1.2 on 2024-11-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_acct_resident_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acct_resident_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='invoice_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='invoice_postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
