# Generated by Django 5.1.2 on 2024-11-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDRSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.CharField(max_length=100)),
                ('discount_code', models.CharField(max_length=5)),
                ('d_product', models.CharField(max_length=10)),
                ('volume_units', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('serial_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('date_index', models.CharField(max_length=100)),
            ],
        ),
    ]
