# Generated by Django 5.1.2 on 2024-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
