# Generated by Django 5.1.2 on 2024-11-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0002_cdrsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='date_index',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='datestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cdrsummary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cdrsummary',
            name='date_index',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cdrsummary',
            name='datestamp',
            field=models.DateTimeField(),
        ),
    ]
