# Generated by Django 5.1.2 on 2024-11-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0003_alter_cdr_date_alter_cdr_date_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdr',
            old_name='date',
            new_name='date_only',
        ),
        migrations.RenameField(
            model_name='cdr',
            old_name='datestamp',
            new_name='date_stamp',
        ),
        migrations.RenameField(
            model_name='cdrsummary',
            old_name='date',
            new_name='date_only',
        ),
        migrations.RenameField(
            model_name='cdrsummary',
            old_name='datestamp',
            new_name='date_stamp',
        ),
        migrations.AlterUniqueTogether(
            name='cdr',
            unique_together={('serial_number', 'date_stamp', 'd_product', 'msg_id')},
        ),
    ]
