# Generated by Django 5.1.2 on 2024-11-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0005_alter_cdr_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cdr',
            unique_together={('serial_number', 'date_stamp', 'd_product', 'msg_id', 'record_id')},
        ),
    ]
