# Generated by Django 5.1.2 on 2024-11-27 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedNRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=225, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='networkreport/csvs/')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_id', models.IntegerField()),
                ('serial_number', models.CharField(max_length=64)),
                ('terminal_id', models.CharField(max_length=64, null=True)),
                ('activated', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('sid', models.CharField(max_length=64, null=True)),
                ('psn', models.CharField(max_length=64, null=True)),
                ('mode', models.CharField(max_length=64)),
                ('feature_options', models.CharField(max_length=64)),
                ('profile_id', models.IntegerField()),
                ('profile_name', models.CharField(max_length=64)),
                ('profiles', models.IntegerField()),
                ('ip_service_address', models.CharField(max_length=64, null=True)),
            ],
            options={
                'unique_together': {('sp_id', 'serial_number', 'activated', 'profile_id')},
            },
        ),
    ]
