# Generated by Django 5.1.2 on 2024-11-27 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkreport',
            name='activated',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
