# Generated by Django 5.1.2 on 2024-11-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkreport', '0002_alter_networkreport_activated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkreport',
            unique_together={('sp_id', 'serial_number', 'activated', 'profile_id')},
        ),
    ]
