# Generated by Django 5.1.2 on 2024-11-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_manage_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('acct_num', models.CharField(max_length=10)),
                ('profile_id', models.IntegerField()),
                ('serial_number', models.CharField(max_length=64)),
                ('activated', models.DateField()),
                ('deactivated', models.DateField()),
                ('ppid', models.IntegerField()),
                ('modal_name', models.CharField(blank=True, max_length=64)),
                ('internet_mail_id', models.CharField(blank=True, max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
