# Generated by Django 5.1.2 on 2024-11-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deactivated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
