# Generated by Django 5.1.2 on 2024-11-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRecent',
            fields=[
                ('device_manage_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('acct_num', models.CharField(max_length=10)),
                ('profile_id', models.IntegerField()),
                ('serial_number', models.CharField(max_length=64)),
                ('activated', models.DateField()),
                ('deactivated', models.DateField(blank=True, null=True)),
                ('ppid', models.IntegerField()),
            ],
        ),
    ]
