# Generated by Django 5.1.2 on 2024-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RECORD_TYPE', models.CharField(max_length=3)),
                ('RECORD_ID', models.IntegerField()),
                ('DATESTAMP', models.DateTimeField()),
                ('TRANSACTION_TYPE', models.CharField(max_length=3)),
                ('DISCOUNT_CODE', models.CharField(max_length=5)),
                ('D_PRODUCT', models.CharField(max_length=10)),
                ('MSG_ID', models.BigIntegerField()),
                ('VOLUME_UNIT_TYPE', models.CharField(max_length=3)),
                ('VOLUME_UNITS', models.IntegerField()),
                ('ACCESS_ID', models.CharField(max_length=100)),
                ('PROFILE_ID', models.IntegerField()),
                ('MOBILE_ID', models.CharField(max_length=64)),
                ('REGION', models.CharField(max_length=10)),
                ('AMOUNT', models.IntegerField()),
                ('FIELD_TYPE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
