# Generated by Django 5.1.2 on 2024-10-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_cdr_datarecord_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CDR',
        ),
        migrations.DeleteModel(
            name='DataRecord',
        ),
    ]
