# Generated by Django 5.1.2 on 2024-10-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdr',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='cdr',
            name='access_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='region',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
