# Generated by Django 5.1.2 on 2024-10-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cdr_field_type_alter_cdr_access_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkreport',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='networkreport',
            name='ip_service_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkreport',
            name='psn',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='networkreport',
            name='sid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='networkreport',
            name='terminal_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
